/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SchoolSlugRouteImport } from './routes/school.$slug'
import { Route as DashboardSchoolsRouteImport } from './routes/dashboard.schools'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardNotesRouteImport } from './routes/dashboard.notes'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard.finance'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SchoolSlugRoute = SchoolSlugRouteImport.update({
  id: '/school/$slug',
  path: '/school/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSchoolsRoute = DashboardSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/schools': typeof DashboardSchoolsRoute
  '/school/$slug': typeof SchoolSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/schools': typeof DashboardSchoolsRoute
  '/school/$slug': typeof SchoolSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/schools': typeof DashboardSchoolsRoute
  '/school/$slug': typeof SchoolSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/dashboard'
    | '/login'
    | '/dashboard/calendar'
    | '/dashboard/finance'
    | '/dashboard/inventory'
    | '/dashboard/notes'
    | '/dashboard/orders'
    | '/dashboard/schools'
    | '/school/$slug'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/dashboard/calendar'
    | '/dashboard/finance'
    | '/dashboard/inventory'
    | '/dashboard/notes'
    | '/dashboard/orders'
    | '/dashboard/schools'
    | '/school/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/dashboard'
    | '/login'
    | '/dashboard/calendar'
    | '/dashboard/finance'
    | '/dashboard/inventory'
    | '/dashboard/notes'
    | '/dashboard/orders'
    | '/dashboard/schools'
    | '/school/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SchoolSlugRoute: typeof SchoolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/school/$slug': {
      id: '/school/$slug'
      path: '/school/$slug'
      fullPath: '/school/$slug'
      preLoaderRoute: typeof SchoolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/schools': {
      id: '/dashboard/schools'
      path: '/schools'
      fullPath: '/dashboard/schools'
      preLoaderRoute: typeof DashboardSchoolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSchoolsRoute: typeof DashboardSchoolsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSchoolsRoute: DashboardSchoolsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SchoolSlugRoute: SchoolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
