/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardEbatlamaRouteImport } from './routes/dashboard.ebatlama'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard.finance'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardHamMaddeRouteImport } from './routes/dashboard.ham-madde'
import { Route as DashboardMaliyetRouteImport } from './routes/dashboard.maliyet'
import { Route as DashboardNotesRouteImport } from './routes/dashboard.notes'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardPhotographersRouteImport } from './routes/dashboard.photographers'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardSchoolsRouteImport } from './routes/dashboard.schools'
import { Route as PortalSchoolIdRouteImport } from './routes/portal.$schoolId'
import { Route as SchoolSlugRouteImport } from './routes/school.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEbatlamaRoute = DashboardEbatlamaRouteImport.update({
  id: '/ebatlama',
  path: '/ebatlama',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHamMaddeRoute = DashboardHamMaddeRouteImport.update({
  id: '/ham-madde',
  path: '/ham-madde',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaliyetRoute = DashboardMaliyetRouteImport.update({
  id: '/maliyet',
  path: '/maliyet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPhotographersRoute = DashboardPhotographersRouteImport.update({
  id: '/photographers',
  path: '/photographers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchoolsRoute = DashboardSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalSchoolIdRoute = PortalSchoolIdRouteImport.update({
  id: '/portal/$schoolId',
  path: '/portal/$schoolId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolSlugRoute = SchoolSlugRouteImport.update({
  id: '/school/$slug',
  path: '/school/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/ebatlama': typeof DashboardEbatlamaRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/ham-madde': typeof DashboardHamMaddeRoute
  '/dashboard/maliyet': typeof DashboardMaliyetRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/photographers': typeof DashboardPhotographersRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/schools': typeof DashboardSchoolsRoute
  '/portal/$schoolId': typeof PortalSchoolIdRoute
  '/school/$slug': typeof SchoolSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/ebatlama': typeof DashboardEbatlamaRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/maliyet': typeof DashboardMaliyetRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/photographers': typeof DashboardPhotographersRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/schools': typeof DashboardSchoolsRoute
  '/portal/$schoolId': typeof PortalSchoolIdRoute
  '/school/$slug': typeof SchoolSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/ebatlama': typeof DashboardEbatlamaRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/maliyet': typeof DashboardMaliyetRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/photographers': typeof DashboardPhotographersRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/schools': typeof DashboardSchoolsRoute
  '/portal/$schoolId': typeof PortalSchoolIdRoute
  '/school/$slug': typeof SchoolSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/dashboard'
    | '/login'
    | '/dashboard/calendar'
    | '/dashboard/ebatlama'
    | '/dashboard/finance'
    | '/dashboard/inventory'
    | '/dashboard/ham-madde'
    | '/dashboard/maliyet'
    | '/dashboard/notes'
    | '/dashboard/orders'
    | '/dashboard/photographers'
    | '/dashboard/portfolio'
    | '/dashboard/schools'
    | '/portal/$schoolId'
    | '/school/$slug'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/dashboard/calendar'
    | '/dashboard/ebatlama'
    | '/dashboard/finance'
    | '/dashboard/inventory'
    | '/dashboard/ham-madde'
    | '/dashboard/maliyet'
    | '/dashboard/notes'
    | '/dashboard/orders'
    | '/dashboard/photographers'
    | '/dashboard/portfolio'
    | '/dashboard/schools'
    | '/portal/$schoolId'
    | '/school/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/dashboard'
    | '/login'
    | '/dashboard/calendar'
    | '/dashboard/ebatlama'
    | '/dashboard/finance'
    | '/dashboard/inventory'
    | '/dashboard/ham-madde'
    | '/dashboard/maliyet'
    | '/dashboard/notes'
    | '/dashboard/orders'
    | '/dashboard/photographers'
    | '/dashboard/portfolio'
    | '/dashboard/schools'
    | '/portal/$schoolId'
    | '/school/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalSchoolIdRoute: typeof PortalSchoolIdRoute
  SchoolSlugRoute: typeof SchoolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ebatlama': {
      id: '/dashboard/ebatlama'
      path: '/ebatlama'
      fullPath: '/dashboard/ebatlama'
      preLoaderRoute: typeof DashboardEbatlamaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ham-madde': {
      id: '/dashboard/ham-madde'
      path: '/ham-madde'
      fullPath: '/dashboard/ham-madde'
      preLoaderRoute: typeof DashboardHamMaddeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/maliyet': {
      id: '/dashboard/maliyet'
      path: '/maliyet'
      fullPath: '/dashboard/maliyet'
      preLoaderRoute: typeof DashboardMaliyetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/photographers': {
      id: '/dashboard/photographers'
      path: '/photographers'
      fullPath: '/dashboard/photographers'
      preLoaderRoute: typeof DashboardPhotographersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schools': {
      id: '/dashboard/schools'
      path: '/schools'
      fullPath: '/dashboard/schools'
      preLoaderRoute: typeof DashboardSchoolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/$schoolId': {
      id: '/portal/$schoolId'
      path: '/portal/$schoolId'
      fullPath: '/portal/$schoolId'
      preLoaderRoute: typeof PortalSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/$slug': {
      id: '/school/$slug'
      path: '/school/$slug'
      fullPath: '/school/$slug'
      preLoaderRoute: typeof SchoolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardEbatlamaRoute: typeof DashboardEbatlamaRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardHamMaddeRoute: typeof DashboardHamMaddeRoute
  DashboardMaliyetRoute: typeof DashboardMaliyetRoute
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPhotographersRoute: typeof DashboardPhotographersRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardSchoolsRoute: typeof DashboardSchoolsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardEbatlamaRoute: DashboardEbatlamaRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardHamMaddeRoute: DashboardHamMaddeRoute,
  DashboardMaliyetRoute: DashboardMaliyetRoute,
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPhotographersRoute: DashboardPhotographersRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardSchoolsRoute: DashboardSchoolsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalSchoolIdRoute: PortalSchoolIdRoute,
  SchoolSlugRoute: SchoolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
